name: Maven CI/CD

on:
 push:
    branches: [ "master" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: check out the repo
       uses: actions/checkout@v4
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DARHAREL_USERNAME }}
         password: ${{ secrets.DARHAREL_TOKEN }}
     - name: Build and push
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: darharel/dhrepo:latest
         build-args: "VERSION=1.0.${{github.run_number}}"
