name: Maven CI/CD

on:
  push:
    branches: [ "master" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      # Add Git Secrets scanning step before the build process
      - name: Git Secrets Scan
        run: git secrets --scan
      
      # Additional steps for building Docker image, etc.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DARHAREL_USERNAME }}
          password: ${{ secrets.DARHAREL_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: darharel/dhrepo:latest
          build-args: "VERSION=1.0.${{github.run_number}}"
